server {
    listen 80;
    server_name _;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Sensors
    location /sensors {
        proxy_pass http://192.168.1.50/sensors_v2;
    }

    # PM2.5 Average
    location /pm25 {
        proxy_pass http://192.168.1.100:8008/pm25/avg;
    }

    # Alerts
    location /alerts {
        proxy_pass http://192.168.1.100:8008/alerts/remark;
    }
}
